# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
       - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: javaapp
    restart: always
    links:
       - "db:database"
    ports:
      - 80:8080
